// <auto-generated/>
#pragma warning disable CS0618
using Kiota.RestApi.Projects.ByCategory.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kiota.RestApi.Projects.ByCategory
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\by-category
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ByCategoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kiota.RestApi.projects.byCategory.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Kiota.RestApi.Projects.ByCategory.Item.WithCategoryItemRequestBuilder"/></returns>
        public global::Kiota.RestApi.Projects.ByCategory.Item.WithCategoryItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("categoryId", position);
                return new global::Kiota.RestApi.Projects.ByCategory.Item.WithCategoryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kiota.RestApi.Projects.ByCategory.ByCategoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ByCategoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/by-category", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kiota.RestApi.Projects.ByCategory.ByCategoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ByCategoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/by-category", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
