### call health check
GET {{url}}/health/
Accept: application/json

### call openapi specs
GET {{url}}/openapi/v1.json
Accept: application/json

### init random data in categories
POST {{url}}/categories/init
Accept: application/json

### get all categories
GET {{url}}/categories/all
Accept: application/json

### init random data in projects
POST {{url}}/projects/init
Accept: application/json

### get all projects
GET {{url}}/projects/all
Accept: application/json
