// <auto-generated/>
#pragma warning disable CS0618
using Kiota.RestApi.Categories.All;
using Kiota.RestApi.Categories.Init;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kiota.RestApi.Categories
{
    /// <summary>
    /// Builds and executes requests for operations under \categories
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CategoriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Kiota.RestApi.Categories.All.AllRequestBuilder All
        {
            get => new global::Kiota.RestApi.Categories.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The init property</summary>
        public global::Kiota.RestApi.Categories.Init.InitRequestBuilder Init
        {
            get => new global::Kiota.RestApi.Categories.Init.InitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kiota.RestApi.Categories.CategoriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/categories", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kiota.RestApi.Categories.CategoriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/categories", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
