### checking availability for the project
GET {{url}}/health/
Accept: application/json

### checking availability for the categories controller
GET {{url}}/categories/health/
Accept: application/json

### checking availability for the projects controller
GET {{url}}/projects/health/
Accept: application/json